### ISSUE TITLE
Question on minimizing the JSD loss

### ISSUE THREAD

**Issue by Luvata** [boschresearch/Divide-and-Bind#2]
Thank you for your amazing paper, the results are really impressive.
For a quick look, it seems the `bind_loss` is the JSD loss

https://github.com/boschresearch/Divide-and-Bind/blob/9d7f7a2f78bec0c74af25cfd53746e85b7c2d80b/divide_and_bind/pipeline_divide_and_bind.py#L831

And according to your paper, your loss is L_attend + L_bind. I just wonder if this loss is correct here, or should it be `loss_values = loss_values + bind_loss` since we want to minimize the bind loss to make 2 distributions largely overlapped

**Comment by YumengLi007** [comment]
Hi @Luvata , thanks for your interest. 
The code should be correct. You are right that bind_loss should be minimized. Meanwhile, total variation (in the attendance loss L_attend) should be **maximized**, as you can see from eq(4) in the paper. 
That's why we have '-' in [L831](https://github.com/boschresearch/Divide-and-Bind/blob/9d7f7a2f78bec0c74af25cfd53746e85b7c2d80b/divide_and_bind/pipeline_divide_and_bind.py#L831), and we flip the sign later [here](https://github.com/boschresearch/Divide-and-Bind/blob/9d7f7a2f78bec0c74af25cfd53746e85b7c2d80b/divide_and_bind/pipeline_divide_and_bind.py#L848).

**Comment by Luvata** [comment]
Oh thanks for your prompt response.
I got it!
